### ISSUE TITLE
Error exception:＂Index was out of range＂

### ISSUE THREAD

**Issue by careyandcastle** [RustingRobot/Kea#21]
**Describe the bug**
Hi! Respectable author! I really love your application, but I meet some issue.
I'm trying to download a webtoon manga called "lianaigeming" ([https://www.webtoons.com/zh-hant/romance/lianaigeming/list?title_no=166]) and I got an error exception "Index was out of range" , could you tell me what should I do to avoid it?
![image](https://user-images.githubusercontent.com/94878650/142958237-24f7fdef-0428-44bb-b874-6be151b9a8b0.png)

The information below is the message of exception detail
```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at HtmlAgilityPack.HtmlNodeCollection.get_Item(Int32 index)
   at Kea.Main.<GetChapterAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Kea.Main.<DownloadQueueAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Kea.Main.<startBtn_Click>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4420.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
Kea
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///F:/user/Downloads/Kea.v1.3.4/Kea.v1.3.4/Kea.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4400.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4360.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4390.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4190.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4390.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
HtmlAgilityPack
    Assembly Version: 1.11.24.0
    Win32 Version: 1.11.24
    CodeBase: file:///F:/user/Downloads/Kea.v1.3.4/Kea.v1.3.4/HtmlAgilityPack.DLL
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

```
**To Reproduce**
1.open  F:\user\Downloads\Kea.v1.3.4\Kea.v1.3.4\Kea.exe
2.enter the link "https://www.webtoons.com/zh-hant/romance/lianaigeming/list?title_no=166"
3.press button "add all to queue"
4.option set to "E:\temp"
5.check "each cartoon" and "each chapter" option
6.save chapter as multiple images
7.start

**Kea Version**
What version of Kea were you using?
Kea v.1.3.4

**Image**
![01](https://user-images.githubusercontent.com/94878650/142959152-270fd0d5-8745-440a-8bfb-0af23859646d.png)
![02](https://user-images.githubusercontent.com/94878650/142959155-5c5c7ee5-0c4a-4394-9222-6541d6fde0f6.png)
![03](https://user-images.githubusercontent.com/94878650/142959157-5b1d4701-ee29-4128-be56-c33e35286724.png)

**Comment by pzkt** [comment]
I sadly could not reproduce the error. For me it downloaded just fine and I'm unsure on why it did not work for you.
Does Kea stop working directly after you press the start button? 
Does the text after "currently processing" say "scoping tab 1" when Kea stops working?
I would try setting the save path to "D:\Desktop\temp" instead of  "E:\temp" and see if that works. 
(that's the path that I used and it worked)
Sorry for the inconvenience.

**Comment by thedragonfruit** [comment]
Respectable author! I really love your application, but I have same issues with him/her. Text after "currently processing" say "scoping tab 3" when Kea stops working

**Comment by thedragonfruit** [comment]
when I download Batman-Wayne-Family-Adventures, the issue show up. But when I download others, it worked well
