### ISSUE TITLE
Unhandled exception

### ISSUE THREAD

**Issue by sohro-da** [RustingRobot/Kea#4]
My input value was "https://www.webtoons.com/en/comedy/mage-and-demon-queen/list?title_no=1438". Stuck at the Season 2, 28-chapter, i.e. 101st folder has been downloaded.
Here just to report the bug (really appreciate this tool, thank you~):

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ArgumentOutOfRangeException: Value of '101' is not valid for 'Value'. 'Value' should be between 'minimum' and 'maximum'.
Parameter name: Value
   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   at System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
   at System.Windows.Forms.Control.Invoke(Delegate method)
   at Kea.Main.downloadComic(Int32 t) in D:\Dokumente\Programmierung\C# Projects\remote\Kea\Kea\Main.cs:line 224
   at Kea.Main.<>c__DisplayClass22_1.<DownloadQueueAsync>b__1() in D:\Dokumente\Programmierung\C# Projects\remote\Kea\Kea\Main.cs:line 148
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Kea.Main.<DownloadQueueAsync>d__22.MoveNext() in D:\Dokumente\Programmierung\C# Projects\remote\Kea\Kea\Main.cs:line 148
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Kea.Main.<startBtn_Click>d__21.MoveNext() in D:\Dokumente\Programmierung\C# Projects\remote\Kea\Kea\Main.cs:line 121
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4250.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
Kea
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/user/Desktop/Kea%20v1.3.0/Kea.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4270.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4200.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4190.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4270.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
HtmlAgilityPack
    Assembly Version: 1.11.24.0
    Win32 Version: 1.11.24
    CodeBase: file:///C:/Users/user/Desktop/Kea%20v1.3.0/HtmlAgilityPack.DLL
----------------------------------------
itextsharp
    Assembly Version: 5.5.13.1
    Win32 Version: 5.5.13.1
    CodeBase: file:///C:/Users/user/Desktop/Kea%20v1.3.0/itextsharp.DLL
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
```

**Comment by pzkt** [comment]
Thanks for reporting the issue!
What Kea version are you using?

**Comment by sohro-da** [comment]
@RustingRobot, um, sorry for late response. It was Kea 1.3.0
But after the bug, I've re-opened the tool and successfully downloaded the rest of the manga (manga 🤔) starting from 101st folder ^_^ 
Aaand, I want to add something else I'm concerned about: the manga is downloaded but naming is a bit wrong that the manga reader reads it in the wrong order (page 0, page 1 and page 10). Though the problem solves simply by adding the extra digits (e.g. page0001, page0002).
Thank you again for the tool ))

**Comment by pzkt** [comment]
v1.3.1 should hopefully solve the bug.
About the naming of files, this is an annoying problem with 'sort by alphabet'. If its possible you could try to 'sort by date created' but other than that I don't think there is an elegant solution (appending zeros to the name)
